name: collect
on:
  schedule:
    - cron: "0 * * * *"   # каждый час
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python scripts/collector.py
      - name: Commit data
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add data/catalog.csv
          git commit -m "update catalog" || echo "no changes"
          git push
