name: post-telegram
on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/_posts/**'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Detect new posts
        id: changes
        run: |
          echo "files<<EOF" >> $GITHUB_OUTPUT
          git diff --name-only HEAD~1 HEAD | grep '^docs/_posts/.*\.md$' || true >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Send to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SITE_URL: ${{ secrets.SITE_URL }}
        run: |
          python scripts/post_telegram.py ${{ steps.changes.outputs.files }}
