name: write
on:
  schedule:
    - cron: "30 6 * * *"   # ежедневно 06:30 UTC
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python scripts/writer.py
      - name: Commit posts
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add docs/_posts/*.md data/published.csv
          git commit -m "new posts" || echo "no changes"
          git push
