name: trends
on:
  schedule:
    - cron:  '10 6 * * *'   # каждый день 06:10 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build weekly trends page
        run: python scripts/trends.py
      - name: Commit report
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add docs/trends/index.md
          git commit -m "Update trends report" || echo "no changes"
          git push
